---
title: "Digital Politics"
subtitle: "Sciences Po Bordeaux"
author: "Instructor: *Mickael Temporão*"
---

The syllabus is tentative and will continue to evolve. I kindly advise you to check it regularly.

# Overview

What do citizens think about politics and why does it matter? This course introduces students to the dynamics of public opinion and political behaviour. It will provide students with a theoretical understanding of the nature and origins of public opinion. We will explore the mechanisms through which citizens’ attitudes and behaviours are formed, organized, and altered over time. We will discuss the role of public opinion and its implications in democratic societies. The course will also introduce students to the modern practice of public opinion, going beyond traditional survey-based approaches, and engaging them with cutting-edge research that relies on digital trace data to address longstanding questions in political science.

## Learning objectives

- writing skills
- media and information literacy
- critical thinking and research skills
- collaboration

# Structure

Asynchronous learning:

This course is delivered through asynchronous learning activities. Each week you will have to complete different activities, such as reading scientific articles, writing short summaries about different topics or recording a video presentation among other. You will have to manage your time to successfully meet the weekly deliverables. More details will be shared with you shortly. There is no preparation required for the first week.

Asynchronous Activities


- Summaries
- Review
-
such as completing advance reading.

do the required readings  for each week.

Each week will build upon the contents of the previous ones.


Prepare a research outline and a presentation and submit an essay.

Students are expected to complete advance reading, watch videos, summarise their learnings, prepare a research outline, do a presentation and submit an essay.

# Grading

5% each (x4) Participation grade for early Wikipedia exercises

10% Participation in class blog or class discussions

10% Peer reviews and collaborations with classmates

50% Quality of your main Wiki contributions

10% Reflective essay

In this course students are expected to produce:

Outline
    - A 500 word problem statement / rationale / research question.
Presentation
    - A 5 minute video presentation.
Paper
    - An 3000 words essay.


## Participation (30%)
## Reports (30%)

## Project (40%)

Structure
Pertinence
Ancrage théorique
Innovation
Argumentaire

## Readings

\@salganik2019bit
\@vaccari2013digital
\@coleman2015handbook


# Licence & Credit

Science should be open, and this course builds up other open licensed material. Unless otherwise noted, all materials for this class are licensed under the [GNU Affero General Public License v3.0](https://spdx.org/licenses/AGPL-3.0-or-later.html).

The source code and the materials to build this website are on GitHub at [mickaeltemporao/CM3A-DP](https://github.com/mickaeltemporao/CM3A-DP)

## Bugs & Feedback

If you have suggestions, find a typo, or any other issue on this website, please go to [issues](https://github.com/mickaeltemporao/CM3A-DP/issues), click on the "New Issue" button to create a new issue, and describe the problem.

